version: '3'

networks:
  ecovacs_stack:
    internal: true
services:
  mysql:
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
      - MYSQL_DATABASE=dev
      - TZ=Europe/Vienna
    networks:
      ecovacs_stack:
      default:
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/mysql.conf.d:/etc/mysql/conf.d
      - ./mysql/scripts/init.sql:/docker-entrypoint-initdb.d/1.sql
    restart: unless-stopped

  backend:
    depends_on:
      - mysql
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      ecovacs_stack:
      default:
    volumes:
      - ./backend:/opt/app
    user: '${UID}:${GID}'
    environment:
      - BASE_URL=https://localhost
      - BASE_URL_01=https://ecovacs.com
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
      - MYSQL_DATABASE=dev
      - TZ=Europe/Vienna
    command: bash -c './generate_certs.sh && yarn install && yarn run dev'
    stdin_open: true
    restart: unless-stopped

  nginx:
    depends_on:
      - backend
    image: nginx:alpine
    ports:
      - 8883:8883
      - 443:443
      - 3000:3000
      - 8070:80
    networks:
      default:
      ecovacs_stack:
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/:/etc/nginx:ro
    restart: unless-stopped

  frontend:
    depends_on:
      - nginx
    build:
      context: ./frontend
      dockerfile: Dockerfile
    user: '${UID}:${GID}'
    environment:
      - WDS_SOCKET_PORT=0
      - TZ=Europe/Vienna
    networks:
      default:
    volumes:
      - ./frontend:/opt/app
    ports:
      - 4200:3000
    command: bash -c 'yarn install && yarn start'
    stdin_open: true
    restart: unless-stopped
